#!/bin/bash
#
# TaktX Community Console Docker Compose Profile Examples
#
# This script shows how to use different profiles
#

echo "=========================================="
echo "TaktX Community Console - Docker Compose Profiles"
echo "=========================================="
echo ""
echo "Available Profiles:"
echo "  - core          : Kafka only (always included)"
echo "  - engine        : TaktX Engine"
echo "  - console       : Platform Service + Ingester + Frontend + Nginx"
echo "  - observability : Prometheus + Grafana + Kafka UI"
echo "  - full          : Everything (default)"
echo ""
echo "=========================================="
echo "Usage Examples:"
echo "=========================================="
echo ""
echo "# Start only Kafka (core)"
echo "docker compose --profile core up -d"
echo "# or just:"
echo "docker compose up -d"
echo ""
echo "# Start Kafka + Console"
echo "docker compose --profile console up -d"
echo ""
echo "# Start Kafka + Engine"
echo "docker compose --profile engine up -d"
echo ""
echo "# Start Kafka + Console + Observability"
echo "docker compose --profile console --profile observability up -d"
echo ""
echo "# Start Kafka + Engine + Console"
echo "docker compose --profile engine --profile console up -d"
echo ""
echo "# Start everything"
echo "docker compose --profile full up -d"
echo ""
echo "=========================================="
echo "Service Mapping:"
echo "=========================================="
echo ""
echo "core (no profile needed - always included):"
echo "  - kafka           : Port 9092, 9094, 9095"
echo ""
echo "engine:"
echo "  - taktx           : Port 8079"
echo ""
echo "console:"
echo "  - taktx-platform-service  : Port 8080"
echo "  - taktx-ingester-inmemory : Port 8084"
echo "  - taktx-console-frontend  : Port 3001"
echo "  - nginx                   : Port 3002"
echo ""
echo "observability:"
echo "  - kafka-ui        : Port 8085"
echo "  - prometheus      : Port 9090"
echo "  - grafana         : Port 3000"
echo ""
echo "full:"
echo "  - All of the above"
echo ""

